export const FLOOR_SIZE = 5;
export const ANIMATION_DURATION = 2000;
export const ACTIONS = {
  HIDE_UNTIL_CLICK: 'HIDE_UNTIL_CLICK',
  START_GAME: 'START_GAME',
  SWAP_ISLANDS: 'SWAP_ISLANDS',
  WAIT: 'WAIT',
  NEXT_PAGE: 'NEXT_PAGE',
  GAME_OVER: 'GAME_OVER',
};
